### ISSUE TITLE
MELD Speakers Mapping

### ISSUE THREAD

**Issue by himanshisyadav** [zerohd4869/DialogueCRN#4]
What is the mapping for the speaker indices in the features file?

**Comment by zerohd4869** [comment]
Thanks for your interest in our work.
The mapping for the speaker indices is 
The examples for using DialogueCRN with RoBERTa features (i.e., IEMOCAP and MELD) are available now. You can see README.md in this repo for details.
If you have any other questions, please feel free to ask me.

**Comment by zerohd4869** [comment]
We found that there is no fixed speaker mapping in the processed MELD features, and different sessions usually have different mappings.
In this work, our method only utilizes the sequence information of speakers, without strictly distinguishing which speaker each utterance belongs to.
If you need this speaker information, I suggest you retrain the features from raw data. Another alternative is to directly align the textual utterance in the features files with the original data (with full speaker information).

**Comment by zerohd4869** [comment]
> What is the mapping for the speaker indices in the features file?

Thanks for your interest in our work.
We found that there is no fixed speaker mapping in the processed MELD features, and different sessions usually have different mappings.
In this work, our method only utilizes the sequence information of speakers, without strictly distinguishing which speaker each utterance belongs to.
If you need this speaker information, I suggest you retrain the features with fixed speaker mapping from raw data. Another alternative is to directly align the textual utterance in the features file with the original data (with full speaker information).
