### ISSUE TITLE
processed data files in COSMIC

### ISSUE THREAD

**Issue by shirly-24** [zerohd4869/DialogueCRN#5]
Could you offer the sample of how to use the processed data files in COSMIC? Thanks.

**Comment by zerohd4869** [comment]
> Could you offer the sample of how to use the processed data files in COSMIC? Thanks.

Thanks for your interest in our work.
The examples for using DialogueCRN with RoBERTa features (i.e., IEMOCAP and MELD) are available now. You can see README.md in this repo for details.
If you have any other questions, please feel free to ask me.

**Comment by wep000** [comment]
I'm sorry to bother you, but can you provide a fine-tuned roberta model? My GPU doesn't support fine-tuning robert, but I want to extract the features of the text myself.
